--1--
CREATE TABLESPACE default_tbs DATAFILE 'C:\tbs_default.dat'  SIZE 100M  AUTOEXTEND ON  ONLINE;
CREATE TEMPORARY TABLESPACE temp_temptbs TEMPFILE 'C:\temp_temp.dat' SIZE 100M AUTOEXTEND ON;

--2--
CREATE USER DBAASSOCIATION IDENTIFIED BY psw Default Tablespace default_tbs Temporary Tablespace temp_temptbs;

--3--
GRANT ALL privileges to  DBAASSOCIATION;

--4--
--MEMBERS--
CREATE TABLE MEMBRES (NUMERO_MBR integer, 
       NOM_MBR varchar(100), 
       DATE_ADHESION_MBR date, 
       ADRESSE_MBR varchar(200),
       constraint PK_MEMBRES primary key (NUMERO_MBR));
--CONGRES--
CREATE TABLE CONGRES (CODE_CGN integer, 
       THEME_CGN varchar(100), 
       PAYS_CGN varchar(100), 
       DUREE_CGN varchar(50) ,
       NB_PARTICIPANT_CGN integer,
       MONTANT_FIXE integer,
       MONTANT_TOTAL_COTISE integer,
       constraint PK_CONGRES primary key (CODE_CGN));
--PARTICIPATIONS--
CREATE TABLE PARTICIPATIONS (NUMERO_MBR integer, 
        CODE_CGN integer,
        MONTANT_COTISE integer,
constraint PK_PARTICIPATIONS primary key(NUMERO_MBR,CODE_CGN),
constraint FK_NUMERO_MBR FOREIGN key (NUMERO_MBR) REFERENCES MEMBRES (NUMERO_MBR) on delete cascade,
constraint FK_CODE_CGN FOREIGN key (CODE_CGN) REFERENCES CONGRES (CODE_CGN) on delete cascade );

--5--
--a--
ALTER TABLE CONGRES ADD CONSTRAINT check_NB_PARTICIPANT_CGN CHECK(NB_PARTICIPANT_CGN IS NOT NULL);
--b--
ALTER TABLE MEMBRES ADD CONSTRAINT check_NOM_MBR CHECK (NOM_MBR IS NOT NULL );
--c--
--MONTANT_COTISE--
ALTER TABLE PARTICIPATIONS ADD CONSTRAINT check_MONTANT_COTISE CHECK (MONTANT_COTISE>0);
--MONTANT_FIXE--
ALTER TABLE CONGRES ADD CONSTRAINT check_MONTANT_FIXE CHECK (MONTANT_FIXE>0);
--MONTANT_TOTAL_COTISE--
ALTER TABLE CONGRES ADD CONSTRAINT check_MONTANT_TOTAL_COTISE CHECK (MONTANT_TOTAL_COTISE>0);
--d--
ALTER TABLE CONGRES ADD UNIQUE (THEME_CGN);
--e--
ALTER TABLE CONGRES ADD CONSTRAINT check_MONTANT_PARTICIPANT CHECK (MONTANT_TOTAL_COTISE/NB_PARTICIPANT_CGN>MONTANT_FIXE);
--f--
CREATE OR REPLACE TRIGGER MAJ_PARTICIPANT_TOTAL_COTISE
 AFTER INSERT ON PARTICIPATIONS
 FOR EACH ROW
 BEGIN
UPDATE CONGRES C SET MONTANT_TOTAL_COTISE = MONTANT_TOTAL_COTISE  + :NEW.MONTANT_COTISE   WHERE C.CODE_CGN = :NEW.CODE_CGN;
DBMS_OUTPUT.PUT_LINE('Montant total cotisé modifié');

UPDATE CONGRES C SET NB_PARTICIPANT_CGN = NB_PARTICIPANT_CGN +1  WHERE C.CODE_CGN = :NEW.CODE_CGN;
	DBMS_OUTPUT.PUT_LINE('Nombre de participants modifié');

 END;
 /

--6--
--MEMBERS--
INSERT INTO MEMBRES VALUES (1 , 'Cherifa MAHBOUBA' , '01/01/2020' , ' Algérie');
INSERT INTO MEMBRES VALUES (2 , 'Lamia TAHMI' , '02/02/2021' , 'Belgique');
INSERT INTO MEMBRES VALUES (3 , 'Chahinez MELEK' , '03/03/2022' , 'Canada');
--CONGRES--
INSERT INTO CONGRES VALUES (1, 'Intelligence Artificielle’ , ’USA’ , ’Une semaine' , 50 , 600 , 35000);
INSERT INTO CONGRES VALUES (2, 'Médecine’ , ’Belgique’ , ’3 jours' , 400 , 125 , 60000);
INSERT INTO CONGRES VALUES (3, 'E-commerce’ , ’Japon’ , ’2 semaines' , 800 , 875 , 900000 );
--PARTICIPATIONS--
INSERT INTO PARTICIPATIONS VALUES (1 , 1 , 700);
INSERT INTO PARTICIPATIONS VALUES (2 , 2 , 500);
INSERT INTO PARTICIPATIONS VALUES (3 , 3 , 1000);
--7--
SELECT M.NUMERO_MBR, M.NOM_MBR, C.THEME_CGN, P.MONTANT_COTISE  
  FROM CONGRES C, MEMBRES M, PARTICIPATIONS P
  WHERE M.NUMERO_MBR=P.NUMERO_MBR AND C.CODE_CGN=P.CODE_CGN;
--8--
SELECT CODE_CGN, THEME_CGN,NB_PARTICIPANT_CGN FROM CONGRES
--9--
CREATE OR REPLACE VIEW COTISATION AS
  (SELECT MAX(MONTANT_TOTAL_COTISE) “MAX”
  FROM CONGRES);

SELECT CODE_CGN, THEME_CGN, MONTANT_TOTAL_COTISE
  FROM  CONGRES C, COTISATION K 
  WHERE  C.MONTANT_TOTAL_COTISE=K.MAX;